name: Deploy Demo to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.152.2'
          extended: true

      - name: Inject Recipe Content
        run: |
          mkdir -p src/site/content/recipes
          cp -r recipes/* src/site/content/recipes/

      - name: Build
        working-directory: ./src/site
        run: hugo --minify --baseURL "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"

      - name: Install Mock Pages
        working-directory: ./src/site
        run: |
          mkdir -p public/add
          cp static/demo_add.html public/add/index.html
          cp static/demo_editor.html public/add/editor.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/site/public